In [4]:
import pandas as pd
import numpy as np
import os

# os.listdir('./goodbooks-10k/')

In [40]:
books = pd.read_csv('books.csv', encoding='ISO-8859-1')
books.head()

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_count,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,4780653,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPrÃ©",1997.0,Harry Potter and the Philosopher's Stone,...,4602479,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,3866839,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,To Kill a Mockingbird,...,3198671,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,...,2683664,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...

In [41]:
ratings = pd.read_csv('ratings.csv', encoding='ISO-8859-1')
ratings.head()

   book_id  user_id  rating
0        1      314       5
1        1      439       3
2        1      588       5
3        1     1169       4
4        1     1185       4

In [42]:
book_tags = pd.read_csv('book_tags.csv', encoding='ISO-8859-1')
book_tags.head()

   goodreads_book_id  tag_id   count
0                  1   30574  167697
1                  1   11305   37174
2                  1   11557   34173
3                  1    8717   12986
4                  1   33114   12716

In [43]:
tags = pd.read_csv('tags.csv')
tags.tail()

       tag_id    tag_name
34247   34247   Ｃhildrens
34248   34248   Ｆａｖｏｒｉｔｅｓ
34249   34249       Ｍａｎｇａ
34250   34250      ＳＥＲＩＥＳ
34251   34251  ｆａｖｏｕｒｉｔｅｓ

In [44]:
tags_join_DF = pd.merge(book_tags, tags, left_on='tag_id', right_on='tag_id', how='inner')
tags_join_DF

        goodreads_book_id  tag_id   count     tag_name
0                       1   30574  167697      to-read
1                       2   30574   24549      to-read
2                       3   30574  496107      to-read
3                       5   30574   11909      to-read
4                       6   30574     298      to-read
...                   ...     ...     ...          ...
999907           31538635   14690       6     hogwarts
999908           32848471   16149      21     jan-2017
999909           33288638   27821       9   single-mom
999910           33288638   11478       7  fave-author
999911           33288638   27939       7     slowburn

[999912 rows x 4 columns]

In [45]:
to_read = pd.read_csv('to_read.csv')
to_read

        user_id  book_id
0             1      112
1             1      235
2             1      533
3             1     1198
4             1     1874
...         ...      ...
912700    53424     4716
912701    53424     4844
912702    53424     5907
912703    53424     7569
912704    53424     8859

[912705 rows x 2 columns]

In [46]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(analyzer='word', ngram_range=(1,2), min_df=0, stop_words='english')
tfidf_matrix = tf.fit_transform(books['authors'])
tfidf_matrix

<10000x14742 sparse matrix of type '<class 'numpy.float64'>'
	with 43235 stored elements in Compressed Sparse Row format>

In [47]:
from sklearn.metrics.pairwise import linear_kernel

cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
cosine_sim

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [48]:
titles = books['title']
indices = pd.Series(books.index, index=books['title'])
indices['The Hobbit']

6

In [49]:
cosine_sim[indices['The Hobbit']]

array([0., 0., 0., ..., 0., 0., 0.])

In [50]:
list(enumerate(cosine_sim[indices['The Hobbit']]))

[(0, 0.0),
 (1, 0.0),
 (2, 0.0),
 (3, 0.0),
 (4, 0.0),
 (5, 0.0),
 (6, 1.0),
 (7, 0.0),
 (8, 0.0),
 (9, 0.0),
 (10, 0.0),
 (11, 0.0),
 (12, 0.0),
 (13, 0.0),
 (14, 0.0),
 (15, 0.0),
 (16, 0.0),
 (17, 0.0),
 (18, 1.0),
 (19, 0.0),
 (20, 0.0),
 (21, 0.0),
 (22, 0.0),
 (23, 0.0),
 (24, 0.0),
 (25, 0.0),
 (26, 0.0),
 (27, 0.0),
 (28, 0.0),
 (29, 0.0),
 (30, 0.0),
 (31, 0.0),
 (32, 0.0),
 (33, 0.0),
 (34, 0.0),
 (35, 0.0),
 (36, 0.0),
 (37, 0.0),
 (38, 0.0),
 (39, 0.0),
 (40, 0.0),
 (41, 0.0),
 (42, 0.0),
 (43, 0.0),
 (44, 0.0),
 (45, 0.0),
 (46, 0.0),
 (47, 0.0),
 (48, 0.0),
 (49, 0.0),
 (50, 0.0),
 (51, 0.0),
 (52, 0.0),
 (53, 0.0),
 (54, 0.0),
 (55, 0.0),
 (56, 0.0),
 (57, 0.0),
 (58, 0.0),
 (59, 0.0),
 (60, 0.0),
 (61, 0.0),
 (62, 0.0),
 (63, 0.0),
 (64, 0.0),
 (65, 0.0),
 (66, 0.0),
 (67, 0.0),
 (68, 0.0),
 (69, 0.0),
 (70, 0.0),
 (71, 0.0),
 (72, 0.0),
 (73, 0.0),
 (74, 0.0),
 (75, 0.0),
 (76, 0.0),
 (77, 0.0),
 (78, 0.0),
 (79, 0.0),
 (80, 0.0),
 (81, 0.0),
 (82, 0.0),
 (83, 0.0),
 (84, 0.0),
 (85, 0.0),
 (86, 0.0),
 (87, 0.0),
 (88, 0.0),
 (89, 0.0),
 (90, 0.0),
 (91, 0.0),
 (92, 0.0),
 (93, 0.0),
 (94, 0.0),
 (95, 0.0),
 (96, 0.0),
 (97, 0.0),
 (98, 0.0),
 (99, 0.0),
 (100, 0.0),
 (101, 0.0),
 (102, 0.0),
 (103, 0.0),
 (104, 0.0),
 (105, 0.0),
 (106, 0.0),
 (107, 0.0),
 (108, 0.0),
 (109, 0.0),
 (110, 0.0),
 (111, 0.0),
 (112, 0.0),
 (113, 0.0),
 (114, 0.0),
 (115, 0.0),
 (116, 0.0),
 (117, 0.0),
 (118, 0.0),
 (119, 0.0),
 (120, 0.0),
 (121, 0.0),
 (122, 0.0),
 (123, 0.0),
 (124, 0.0),
 (125, 0.0),
 (126, 0.0),
 (127, 0.0),
 (128, 0.0),
 (129, 0.0),
 (130, 0.0),
 (131, 0.0),
 (132, 0.0),
 (133, 0.0),
 (134, 0.0),
 (135, 0.0),
 (136, 0.0),
 (137, 0.0),
 (138, 0.0),
 (139, 0.0),
 (140, 0.0),
 (141, 0.0),
 (142, 0.0),
 (143, 0.0),
 (144, 0.0),
 (145, 0.0),
 (146, 0.0),
 (147, 0.0),
 (148, 0.0),
 (149, 0.0),
 (150, 0.0),
 (151, 0.0),
 (152, 0.0),
 (153, 0.0),
 (154, 1.0),
 (155, 0.0),
 (156, 0.0),
 (157, 0.0),
 (158, 0.0),
 (159, 0.0),
 (160, 1.0),
 (161, 0.0),
 (162, 0.0),
 (163, 0.0),
 (164, 0.0),
 (165, 0.0),
 (166, 0.0),
 (167, 0.0),
 (168, 0.0),
 (169, 0.0),
 (170, 0.0),
 (171, 0.0),
 (172, 0.0),
 (173, 0.0),
 (174, 0.0),
 (175, 0.0),
 (176, 0.0),
 (177, 0.0),
 (178, 0.0),
 (179, 0.0),
 (180, 0.0),
 (181, 0.0),
 (182, 0.0),
 (183, 0.0),
 (184, 0.0),
 (185, 0.0),
 (186, 0.0),
 (187, 0.0),
 (188, 1.0),
 (189, 0.0),
 (190, 0.0),
 (191, 0.0),
 (192, 0.0),
 (193, 0.0),
 (194, 0.0),
 (195, 0.0),
 (196, 0.0),
 (197, 0.0),
 (198, 0.0),
 (199, 0.0),
 (200, 0.0),
 (201, 0.0),
 (202, 0.0),
 (203, 0.0),
 (204, 0.0),
 (205, 0.0),
 (206, 0.0),
 (207, 0.0),
 (208, 0.0),
 (209, 0.0),
 (210, 0.0),
 (211, 0.0),
 (212, 0.0),
 (213, 0.0),
 (214, 0.0),
 (215, 0.0),
 (216, 0.0),
 (217, 0.0),
 (218, 0.0),
 (219, 0.0),
 (220, 0.0),
 (221, 0.0),
 (222, 0.0),
 (223, 0.0),
 (224, 0.0),
 (225, 0.0),
 (226, 0.0),
 (227, 0.0),
 (228, 0.0),
 (229, 0.0),
 (230, 0.0),
 (231, 0.0),
 (232, 0.0),
 (233, 0.0),
 (234, 0.0),
 (235, 0.0),
 (236, 0.0),
 (237, 0.0),
 (238, 0.0),
 (239, 0.0),
 (240, 0.0),
 (241, 0.0),
 (242, 0.0),
 (243, 0.0),
 (244, 0.0),
 (245, 0.0),
 (246, 0.0),
 (247, 0.0),
 (248, 0.0),
 (249, 0.0),
 (250, 0.0),
 (251, 0.0),
 (252, 0.0),
 (253, 0.0),
 (254, 0.0),
 (255, 0.0),
 (256, 0.0),
 (257, 0.0),
 (258, 0.0),
 (259, 0.0),
 (260, 0.0),
 (261, 0.0),
 (262, 0.0),
 (263, 0.0),
 (264, 0.0),
 (265, 0.0),
 (266, 0.0),
 (267, 0.0),
 (268, 0.0),
 (269, 0.0),
 (270, 0.0),
 (271, 0.0),
 (272, 0.0),
 (273, 0.0),
 (274, 0.0),
 (275, 0.0),
 (276, 0.0),
 (277, 0.0),
 (278, 0.0),
 (279, 0.0),
 (280, 0.0),
 (281, 0.0),
 (282, 0.0),
 (283, 0.0),
 (284, 0.0),
 (285, 0.0),
 (286, 0.0),
 (287, 0.0),
 (288, 0.0),
 (289, 0.0),
 (290, 0.0),
 (291, 0.0),
 (292, 0.0),
 (293, 0.0),
 (294, 0.0),
 (295, 0.0),
 (296, 0.0),
 (297, 0.0),
 (298, 0.0),
 (299, 0.0),
 (300, 0.0),
 (301, 0.0),
 (302, 0.0),
 (303, 0.0),
 (304, 0.0),
 (305, 0.0),
 (306, 0.0),
 (307, 0.0),
 (308, 0.0),
 (309, 0.0),
 (310, 0.0),
 (311, 0.0),
 (312, 0.0),
 (313, 0.0),
 (314, 0.0),
 (315, 0.0),
 (316, 0.0),
 (317, 0.0),
 (318, 0.0),
 (319, 0.0),
 (320, 0.0),
 (321, 0.0),
 (322, 0.0),
 (323, 0.0),
 (324, 0.0),
 (325, 0.0),
 (326, 0.0),
 (327, 0.0),
 (328, 0.0),
 (329, 0.0),
 (330, 0.0),
 (331, 0.0),
 (332, 0.0),
 (333, 0.0),
 (334, 0.0),
 (335, 0.0),
 (336, 0.0),
 (337, 0.0),
 (338, 0.0),
 (339, 0.0),
 (340, 0.0),
 (341, 0.0),
 (342, 0.0),
 (343, 0.0),
 (344, 0.0),
 (345, 0.0),
 (346, 0.0),
 (347, 0.0),
 (348, 0.0),
 (349, 0.0),
 (350, 0.0),
 (351, 0.0),
 (352, 0.0),
 (353, 0.0),
 (354, 0.0),
 (355, 0.0),
 (356, 0.0),
 (357, 0.0),
 (358, 0.0),
 (359, 0.0),
 (360, 0.0),
 (361, 0.0),
 (362, 0.0),
 (363, 0.0),
 (364, 0.0),
 (365, 0.0),
 (366, 0.0),
 (367, 0.0),
 (368, 0.0),
 (369, 0.0),
 (370, 0.0),
 (371, 0.0),
 (372, 0.0),
 (373, 0.0),
 (374, 0.0),
 (375, 0.0),
 (376, 0.0),
 (377, 0.0),
 (378, 0.0),
 (379, 0.0),
 (380, 0.0),
 (381, 0.0),
 (382, 0.0),
 (383, 0.0),
 (384, 0.0),
 (385, 0.0),
 (386, 0.0),
 (387, 0.0),
 (388, 0.0),
 (389, 0.0),
 (390, 0.0),
 (391, 0.0),
 (392, 0.0),
 (393, 0.0),
 (394, 0.0),
 (395, 0.0),
 (396, 0.0),
 (397, 0.0),
 (398, 0.0),
 (399, 0.0),
 (400, 0.0),
 (401, 0.0),
 (402, 0.0),
 (403, 0.0),
 (404, 0.0),
 (405, 0.0),
 (406, 0.0),
 (407, 0.0),
 (408, 0.0),
 (409, 0.0),
 (410, 0.0),
 (411, 0.0),
 (412, 0.0),
 (413, 0.0),
 (414, 0.0),
 (415, 0.0),
 (416, 0.0),
 (417, 0.0),
 (418, 0.0),
 (419, 0.0),
 (420, 0.0),
 (421, 0.0),
 (422, 0.0),
 (423, 0.0),
 (424, 0.0),
 (425, 0.0),
 (426, 0.0),
 (427, 0.0),
 (428, 0.0),
 (429, 0.0),
 (430, 0.0),
 (431, 0.0),
 (432, 0.0),
 (433, 0.0),
 (434, 0.0),
 (435, 0.0),
 (436, 0.0),
 (437, 0.0),
 (438, 0.0),
 (439, 0.0),
 (440, 0.0),
 (441, 0.0),
 (442, 0.0),
 (443, 0.0),
 (444, 0.0),
 (445, 0.0),
 (446, 0.0),
 (447, 0.0),
 (448, 0.0),
 (449, 0.0),
 (450, 0.0),
 (451, 0.0),
 (452, 0.0),
 (453, 0.0),
 (454, 0.0),
 (455, 0.0),
 (456, 0.0),
 (457, 0.0),
 (458, 0.0),
 (459, 0.0),
 (460, 0.0),
 (461, 0.0),
 (462, 0.0),
 (463, 0.0),
 (464, 0.0),
 (465, 0.24362189060736741),
 (466, 0.0),
 (467, 0.0),
 (468, 0.0),
 (469, 0.0),
 (470, 0.0),
 (471, 0.0),
 (472, 0.0),
 (473, 0.0),
 (474, 0.0),
 (475, 0.0),
 (476, 0.0),
 (477, 0.0),
 (478, 0.0),
 (479, 0.0),
 (480, 0.0),
 (481, 0.0),
 (482, 0.0),
 (483, 0.0),
 (484, 0.0),
 (485, 0.0),
 (486, 0.0),
 (487, 0.0),
 (488, 0.0),
 (489, 0.0),
 (490, 0.0),
 (491, 0.0),
 (492, 0.0),
 (493, 0.0),
 (494, 0.0),
 (495, 0.0),
 (496, 0.0),
 (497, 0.0),
 (498, 0.0),
 (499, 0.0),
 (500, 0.0),
 (501, 0.0),
 (502, 0.0),
 (503, 0.0),
 (504, 0.0),
 (505, 0.0),
 (506, 0.0),
 (507, 0.0),
 (508, 0.0),
 (509, 0.0),
 (510, 0.0),
 (511, 0.0),
 (512, 0.0),
 (513, 0.0),
 (514, 0.0),
 (515, 0.0),
 (516, 0.0),
 (517, 0.0),
 (518, 0.0),
 (519, 0.0),
 (520, 0.0),
 (521, 0.0),
 (522, 0.0),
 (523, 0.0),
 (524, 0.0),
 (525, 0.0),
 (526, 0.0),
 (527, 0.0),
 (528, 0.0),
 (529, 0.0),
 (530, 0.0),
 (531, 0.0),
 (532, 0.0),
 (533, 0.0),
 (534, 0.0),
 (535, 0.0),
 (536, 0.0),
 (537, 0.0),
 (538, 0.0),
 (539, 0.0),
 (540, 0.0),
 (541, 0.0),
 (542, 0.0),
 (543, 0.0),
 (544, 0.0),
 (545, 0.0),
 (546, 0.0),
 (547, 0.0),
 (548, 0.0),
 (549, 0.0),
 (550, 0.0),
 (551, 0.0),
 (552, 0.0),
 (553, 0.0),
 (554, 0.0),
 (555, 0.0),
 (556, 0.0),
 (557, 0.0),
 (558, 0.0),
 (559, 0.0),
 (560, 0.0),
 (561, 0.0),
 (562, 0.0),
 (563, 0.0),
 (564, 0.0),
 (565, 0.0),
 (566, 0.0),
 (567, 0.0),
 (568, 0.0),
 (569, 0.0),
 (570, 0.0),
 (571, 0.0),
 (572, 0.0),
 (573, 0.0),
 (574, 0.0),
 (575, 0.0),
 (576, 0.0),
 (577, 0.0),
 (578, 0.0),
 (579, 0.0),
 (580, 0.0),
 (581, 0.0),
 (582, 0.0),
 (583, 0.0),
 (584, 0.0),
 (585, 0.0),
 (586, 0.0),
 (587, 0.0),
 (588, 0.0),
 (589, 0.0),
 (590, 0.0),
 (591, 0.0),
 (592, 0.0),
 (593, 0.0),
 (594, 0.0),
 (595, 0.0),
 (596, 0.0),
 (597, 0.0),
 (598, 0.0),
 (599, 0.0),
 (600, 0.0),
 (601, 0.0),
 (602, 0.0),
 (603, 0.0),
 (604, 0.0),
 (605, 0.0),
 (606, 0.0),
 (607, 0.0),
 (608, 0.0),
 (609, 0.0),
 (610, 0.5574817139590805),
 (611, 0.0),
 (612, 0.0),
 (613, 0.0),
 (614, 0.0),
 (615, 0.0),
 (616, 0.0),
 (617, 0.0),
 (618, 0.0),
 (619, 0.0),
 (620, 0.0),
 (621, 0.0),
 (622, 0.0),
 (623, 0.0),
 (624, 0.0),
 (625, 0.0),
 (626, 0.0),
 (627, 0.0),
 (628, 0.0),
 (629, 0.0),
 (630, 0.0),
 (631, 0.0),
 (632, 0.0),
 (633, 0.0),
 (634, 0.0),
 (635, 0.0),
 (636, 0.0),
 (637, 0.0),
 (638, 0.0),
 (639, 0.0),
 (640, 0.0),
 (641, 0.0),
 (642, 0.0),
 (643, 0.0),
 (644, 0.0),
 (645, 0.0),
 (646, 0.0),
 (647, 0.0),
 (648, 0.0),
 (649, 0.0),
 (650, 0.0),
 (651, 0.0),
 (652, 0.0),
 (653, 0.0),
 (654, 0.0),
 (655, 0.0),
 (656, 0.0),
 (657, 0.0),
 (658, 0.0),
 (659, 0.0),
 (660, 0.0),
 (661, 0.0),
 (662, 0.0),
 (663, 0.0),
 (664, 0.0),
 (665, 0.0),
 (666, 0.0),
 (667, 0.0),
 (668, 0.0),
 (669, 0.0),
 (670, 0.0),
 (671, 0.0),
 (672, 0.0),
 (673, 0.0),
 (674, 0.0),
 (675, 0.0),
 (676, 0.0),
 (677, 0.0),
 (678, 0.0),
 (679, 0.0),
 (680, 0.0),
 (681, 0.0),
 (682, 0.0),
 (683, 0.0),
 (684, 0.0),
 (685, 0.0),
 (686, 0.0),
 (687, 0.0),
 (688, 0.0),
 (689, 0.0),
 (690, 0.0),
 (691, 0.0),
 (692, 0.0),
 (693, 0.0),
 (694, 0.0),
 (695, 0.0),
 (696, 0.0),
 (697, 0.0),
 (698, 0.0),
 (699, 0.0),
 (700, 0.0),
 (701, 0.0),
 (702, 0.0),
 (703, 0.0),
 (704, 0.0),
 (705, 0.0),
 (706, 0.0),
 (707, 0.0),
 (708, 0.0),
 (709, 0.0),
 (710, 0.0),
 (711, 0.0),
 (712, 0.0),
 (713, 0.0),
 (714, 0.0),
 (715, 0.0),
 (716, 0.0),
 (717, 0.0),
 (718, 0.0),
 (719, 0.0),
 (720, 0.0),
 (721, 0.0),
 (722, 0.0),
 (723, 0.0),
 (724, 0.0),
 (725, 0.0),
 (726, 0.0),
 (727, 0.0),
 (728, 0.0),
 (729, 0.0),
 (730, 0.0),
 (731, 0.0),
 (732, 0.0),
 (733, 0.0),
 (734, 0.0),
 (735, 0.0),
 (736, 0.0),
 (737, 0.0),
 (738, 0.0),
 (739, 0.0),
 (740, 0.0),
 (741, 0.0),
 (742, 0.0),
 (743, 0.0),
 (744, 0.0),
 (745, 0.0),
 (746, 0.0),
 (747, 0.0),
 (748, 0.0),
 (749, 0.0),
 (750, 0.0),
 (751, 0.0),
 (752, 0.0),
 (753, 0.0),
 (754, 0.0),
 (755, 0.0),
 (756, 0.0),
 (757, 0.0),
 (758, 0.0),
 (759, 0.0),
 (760, 0.0),
 (761, 0.0),
 (762, 0.0),
 (763, 0.0),
 (764, 0.0),
 (765, 0.0),
 (766, 0.0),
 (767, 0.0),
 (768, 0.0),
 (769, 0.0),
 (770, 0.0),
 (771, 0.0),
 (772, 0.0),
 (773, 0.0),
 (774, 0.0),
 (775, 0.0),
 (776, 0.0),
 (777, 0.0),
 (778, 0.0),
 (779, 0.0),
 (780, 0.0),
 (781, 0.0),
 (782, 0.0),
 (783, 0.0),
 (784, 0.0),
 (785, 0.0),
 (786, 0.0),
 (787, 0.0),
 (788, 0.0),
 (789, 0.0),
 (790, 0.0),
 (791, 0.0),
 (792, 0.0),
 (793, 0.0),
 (794, 0.0),
 (795, 0.0),
 (796, 0.0),
 (797, 0.0),
 (798, 0.0),
 (799, 0.0),
 (800, 0.0),
 (801, 0.0),
 (802, 0.0),
 (803, 0.0),
 (804, 0.0),
 (805, 0.0),
 (806, 0.0),
 (807, 0.0),
 (808, 0.0),
 (809, 0.0),
 (810, 0.0),
 (811, 0.0),
 (812, 0.0),
 (813, 0.0),
 (814, 0.0),
 (815, 0.0),
 (816, 0.0),
 (817, 0.0),
 (818, 0.0),
 (819, 0.0),
 (820, 0.0),
 (821, 0.0),
 (822, 0.0),
 (823, 0.0),
 (824, 0.0),
 (825, 0.0),
 (826, 0.0),
 (827, 0.0),
 (828, 0.0),
 (829, 0.0),
 (830, 0.0),
 (831, 0.0),
 (832, 0.0),
 (833, 0.0),
 (834, 0.0),
 (835, 0.0),
 (836, 0.0),
 (837, 0.0),
 (838, 0.0),
 (839, 0.0),
 (840, 0.0),
 (841, 0.0),
 (842, 0.0),
 (843, 0.0),
 (844, 0.0),
 (845, 0.0),
 (846, 0.0),
 (847, 0.0),
 (848, 0.0),
 (849, 0.0),
 (850, 0.0),
 (851, 0.0),
 (852, 0.0),
 (853, 0.0),
 (854, 0.0),
 (855, 0.0),
 (856, 0.0),
 (857, 0.0),
 (858, 0.0),
 (859, 0.0),
 (860, 0.0),
 (861, 0.0),
 (862, 0.0),
 (863, 0.0),
 (864, 0.0),
 (865, 0.0),
 (866, 0.0),
 (867, 0.0),
 (868, 0.0),
 (869, 0.0),
 (870, 0.0),
 (871, 0.0),
 (872, 0.0),
 (873, 0.0),
 (874, 0.0),
 (875, 0.0),
 (876, 0.0),
 (877, 0.0),
 (878, 0.0),
 (879, 0.0),
 (880, 0.0),
 (881, 0.0),
 (882, 0.0),
 (883, 0.0),
 (884, 0.0),
 (885, 0.0),
 (886, 0.0),
 (887, 0.0),
 (888, 0.0),
 (889, 0.0),
 (890, 0.0),
 (891, 0.0),
 (892, 0.0),
 (893, 0.0),
 (894, 0.0),
 (895, 0.0),
 (896, 0.0),
 (897, 0.0),
 (898, 0.0),
 (899, 0.0),
 (900, 0.0),
 (901, 0.0),
 (902, 0.0),
 (903, 0.0),
 (904, 0.0),
 (905, 0.0),
 (906, 0.0),
 (907, 0.0),
 (908, 0.0),
 (909, 0.0),
 (910, 0.0),
 (911, 0.0),
 (912, 0.0),
 (913, 0.0),
 (914, 0.0),
 (915, 0.0),
 (916, 0.0),
 (917, 0.0),
 (918, 0.0),
 (919, 0.0),
 (920, 0.0),
 (921, 0.0),
 (922, 0.0),
 (923, 0.0),
 (924, 0.0),
 (925, 0.0),
 (926, 0.0),
 (927, 0.0),
 (928, 0.0),
 (929, 0.0),
 (930, 0.0),
 (931, 0.0),
 (932, 0.0),
 (933, 0.0),
 (934, 0.0),
 (935, 0.0),
 (936, 0.0),
 (937, 0.0),
 (938, 0.0),
 (939, 0.0),
 (940, 0.0),
 (941, 0.0),
 (942, 0.0),
 (943, 0.0),
 (944, 0.0),
 (945, 0.0),
 (946, 0.0),
 (947, 0.0),
 (948, 0.0),
 (949, 0.0),
 (950, 0.0),
 (951, 0.0),
 (952, 0.0),
 (953, 0.0),
 (954, 0.0),
 (955, 0.0),
 (956, 0.0),
 (957, 0.0),
 (958, 0.0),
 (959, 0.0),
 (960, 0.0),
 (961, 0.0),
 (962, 0.0),
 (963, 1.0),
 (964, 0.0),
 (965, 0.0),
 (966, 0.0),
 (967, 0.0),
 (968, 0.0),
 (969, 0.0),
 (970, 0.0),
 (971, 0.0),
 (972, 0.0),
 (973, 0.0),
 (974, 0.0),
 (975, 0.0),
 (976, 0.0),
 (977, 0.0),
 (978, 0.0),
 (979, 0.0),
 (980, 0.0),
 (981, 0.0),
 (982, 0.0),
 (983, 0.0),
 (984, 0.0),
 (985, 0.0),
 (986, 0.0),
 (987, 0.0),
 (988, 0.0),
 (989, 0.0),
 (990, 0.0),
 (991, 0.0),
 (992, 0.0),
 (993, 0.0),
 (994, 0.0),
 (995, 0.0),
 (996, 0.0),
 (997, 0.0),
 (998, 0.0),
 (999, 0.0),
 ...]

In [51]:
sim_scores = list(enumerate(cosine_sim[indices['The Hobbit']]))
sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
sim_scores[:3]

[(6, 1.0), (18, 1.0), (154, 1.0)]

In [52]:
sim_scores = sim_scores[1:11]
book_indices = [i[0] for i in sim_scores]
titles.iloc[book_indices]

18      The Fellowship of the Ring (The Lord of the Ri...
154            The Two Towers (The Lord of the Rings, #2)
160     The Return of the King (The Lord of the Rings,...
188     The Lord of the Rings (The Lord of the Rings, ...
963     J.R.R. Tolkien 4-Book Boxed Set: The Hobbit an...
4975        Unfinished Tales of NÃºmenor and Middle-Earth
2308                               The Children of HÃºrin
610              The Silmarillion (Middle-Earth Universe)
8271                   The Complete Guide to Middle-Earth
1128     The History of the Hobbit, Part One: Mr. Baggins
Name: title, dtype: object

In [53]:
books_with_tags = pd.merge(books, tags_join_DF, left_on='book_id', right_on='goodreads_book_id', how='inner')
books_with_tags.head()

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,goodreads_book_id,tag_id,count,tag_name
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,2767052,30574,11314,to-read
1,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,2767052,11305,10836,fantasy
2,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,2767052,11557,50755,favorites
3,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,2767052,8717,35418,currently-reading
4,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,2767052,33114,25968,young-adult

In [54]:
tf1 = TfidfVectorizer(analyzer='word', ngram_range=(1,2), min_df=0, stop_words='english')
tfidf_matrix1 = tf1.fit_transform(books_with_tags['tag_name'].head(1000))
cosine_sim1 = linear_kernel(tfidf_matrix1, tfidf_matrix1)

In [55]:
titles1 = books['title']
indices1 = pd.Series(books.index, index=books['title'])

def tags_recommendations(title):
    idx = indices1[title]
    sim_scores = list(enumerate(cosine_sim1[idx]))
    sim_scores = sorted(sim_scores, key=lambda x : x[1], reverse=True)
    book_indices = [i[0] for i in sim_scores]
    return titles.iloc[book_indices]

In [56]:
tags_recommendations('The Hobbit')

6                                        The Hobbit
16             Catching Fire (The Hunger Games, #2)
31                                  Of Mice and Men
107    Confessions of a Shopaholic (Shopaholic, #1)
125                       Dune (Dune Chronicles #1)
                           ...
995        Three to Get Deadly (Stephanie Plum, #3)
996                           The Scarlet Pimpernel
997             The Monster at the End of this Book
998     Tales of a Fourth Grade Nothing (Fudge, #1)
999           Shadow and Bone (Shadow and Bone, #1)
Name: title, Length: 1000, dtype: object

In [57]:
temp_df = books_with_tags.groupby('book_id')['tag_name'].apply(' '.join).reset_index()
temp_df.head()

   book_id                                           tag_name
0        1  to-read fantasy favorites currently-reading yo...
1        2  to-read fantasy favorites currently-reading yo...
2        3  to-read fantasy favorites currently-reading yo...
3        5  to-read fantasy favorites currently-reading yo...
4        6  to-read fantasy young-adult fiction harry-pott...

In [58]:
books = pd.merge(books, temp_df, left_on='book_id', right_on='book_id', how='inner')

In [60]:
books.head()

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,work_ratings_count,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,tag_name
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,4942365,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,to-read fantasy favorites currently-reading yo...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPrÃ©",1997.0,Harry Potter and the Philosopher's Stone,...,4800065,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,to-read fantasy favorites currently-reading yo...
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,3916824,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...,to-read fantasy favorites currently-reading yo...
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,To Kill a Mockingbird,...,3340896,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...,to-read favorites currently-reading young-adul...
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,...,2773745,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...,to-read favorites currently-reading young-adul...

In [61]:
books['corpus'] = (pd.Series(books[['authors', 'tag_name']].fillna('').values.tolist()).str.join(' '))

In [62]:
books.head()

,id,book_id,best_book_id,work_id,books_count,isbn,isbn13,authors,original_publication_year,original_title,...,work_text_reviews_count,ratings_1,ratings_2,ratings_3,ratings_4,ratings_5,image_url,small_image_url,tag_name,corpus
0,1,2767052,2767052,2792775,272,439023483,9.780439e+12,Suzanne Collins,2008.0,The Hunger Games,...,155254,66715,127936,560092,1481305,2706317,https://images.gr-assets.com/books/1447303603m...,https://images.gr-assets.com/books/1447303603s...,to-read fantasy favorites currently-reading yo...,Suzanne Collins to-read fantasy favorites curr...
1,2,3,3,4640799,491,439554934,9.780440e+12,"J.K. Rowling, Mary GrandPrÃ©",1997.0,Harry Potter and the Philosopher's Stone,...,75867,75504,101676,455024,1156318,3011543,https://images.gr-assets.com/books/1474154022m...,https://images.gr-assets.com/books/1474154022s...,to-read fantasy favorites currently-reading yo...,"J.K. Rowling, Mary GrandPrÃ© to-read fantasy f..."
2,3,41865,41865,3212258,226,316015849,9.780316e+12,Stephenie Meyer,2005.0,Twilight,...,95009,456191,436802,793319,875073,1355439,https://images.gr-assets.com/books/1361039443m...,https://images.gr-assets.com/books/1361039443s...,to-read fantasy favorites currently-reading yo...,Stephenie Meyer to-read fantasy favorites curr...
3,4,2657,2657,3275794,487,61120081,9.780061e+12,Harper Lee,1960.0,To Kill a Mockingbird,...,72586,60427,117415,446835,1001952,1714267,https://images.gr-assets.com/books/1361975680m...,https://images.gr-assets.com/books/1361975680s...,to-read favorites currently-reading young-adul...,Harper Lee to-read favorites currently-reading...
4,5,4671,4671,245494,1356,743273567,9.780743e+12,F. Scott Fitzgerald,1925.0,The Great Gatsby,...,51992,86236,197621,606158,936012,947718,https://images.gr-assets.com/books/1490528560m...,https://images.gr-assets.com/books/1490528560s...,to-read favorites currently-reading young-adul...,F. Scott Fitzgerald to-read favorites currentl...

In [63]:
tf_corpus = TfidfVectorizer(analyzer='word', ngram_range=(1,2), min_df=0, stop_words='english')
tfidf_matrix_corpus = tf_corpus.fit_transform(books['corpus'])
cosine_sim_corpus = linear_kernel(tfidf_matrix_corpus, tfidf_matrix_corpus)

In [64]:
titles = books['title']
indices = pd.Series(books.index, index = books['title'])

In [65]:
def corpus_recommendations(title):
    idx = indices1[title]
    sim_scores = list(enumerate(cosine_sim_corpus[idx]))
    sim_scores = sorted(sim_scores, key=lambda x : x[1], reverse=True)
    book_indices = [i[0] for i in sim_scores]
    return titles.iloc[book_indices]

In [66]:
corpus_recommendations('The Hobbit')

6                                              The Hobbit
188     The Lord of the Rings (The Lord of the Rings, ...
154            The Two Towers (The Lord of the Rings, #2)
160     The Return of the King (The Lord of the Rings,...
18      The Fellowship of the Ring (The Lord of the Ri...
                              ...
4759       Ø±Ø­ÙØªÙ Ù
Ù Ø§ÙØ´Ù Ø¥ÙÙ Ø§ÙØ¥ÙÙ
Ø§Ù
3596    Lies & the Lying Liars Who Tell Them: A Fair &...
8603                  Edvard Munch: 1863-1944 (Basic Art)
7233                                  Fiddler on the Roof
8403                                  The Gnostic Gospels
Name: title, Length: 10000, dtype: object

In [67]:
corpus_recommendations('Twilight (Twilight, #1)')

2                                 Twilight (Twilight, #1)
51                                 Eclipse (Twilight, #3)
48                                New Moon (Twilight, #2)
991                    The Twilight Saga (Twilight, #1-4)
833                         Midnight Sun (Twilight, #1.5)
                              ...
3596    Lies & the Lying Liars Who Tell Them: A Fair &...
4759       Ø±Ø­ÙØªÙ Ù
Ù Ø§ÙØ´Ù Ø¥ÙÙ Ø§ÙØ¥ÙÙ
Ø§Ù
9458                                       Hands Of Light
7233                                  Fiddler on the Roof
8403                                  The Gnostic Gospels
Name: title, Length: 10000, dtype: object

In [68]:
corpus_recommendations('Romeo and Juliet')

28                                       Romeo and Juliet
352                                               Othello
769                                         Julius Caesar
124                                                Hamlet
153                                               Macbeth
                              ...
7941    Vegan Cupcakes Take Over the World: 75 Dairy-F...
4759       Ø±Ø­ÙØªÙ Ù
Ù Ø§ÙØ´Ù Ø¥ÙÙ Ø§ÙØ¥ÙÙ
Ø§Ù
1755                        M.C. Escher: The Graphic Work
8603                  Edvard Munch: 1863-1944 (Basic Art)
7148                  Forever Peace (The Forever War, #2)
Name: title, Length: 10000, dtype: object